name: enzona
description: SDK para las APIs de Enzona.
version: 0.0.1+1
homepage: https://github.com/luis901101/enzona

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0
  chopper: ^4.0.1
  retrofit: ^2.0.1
  dio: ^4.0.0
  oauth2: ^2.0.0

dev_dependencies:
  json_serializable: ^5.0.2
  chopper_generator: ^4.0.2
  retrofit_generator: ^2.0.1+2
  build_runner: ^2.1.4 #flutter packages pub run build_runner build
  lints: ^1.0.1
  test: ^1.18.2
